//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMBelt.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMBelt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Character.
        /// </summary>
        public static string AllCharacters_DeleteCharacter {
            get {
                return ResourceManager.GetString("AllCharacters_DeleteCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Stats.
        /// </summary>
        public static string AllCharacters_ViewCoreStats {
            get {
                return ResourceManager.GetString("AllCharacters_ViewCoreStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string AllCharacters_ViewItems {
            get {
                return ResourceManager.GetString("AllCharacters_ViewItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spells.
        /// </summary>
        public static string AllCharacters_ViewSpells {
            get {
                return ResourceManager.GetString("AllCharacters_ViewSpells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Character.
        /// </summary>
        public static string ControlPanel_CreateNewCharacter {
            get {
                return ResourceManager.GetString("ControlPanel_CreateNewCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Characters.
        /// </summary>
        public static string ControlPanel_ViewAllCharacters {
            get {
                return ResourceManager.GetString("ControlPanel_ViewAllCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DM-Belt.
        /// </summary>
        public static string MainWindow_DisplayName {
            get {
                return ResourceManager.GetString("MainWindow_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing class.
        /// </summary>
        public static string NewCharacter_Error_NoClass {
            get {
                return ResourceManager.GetString("NewCharacter_Error_NoClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing name.
        /// </summary>
        public static string NewCharacter_Error_NoName {
            get {
                return ResourceManager.GetString("NewCharacter_Error_NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing race.
        /// </summary>
        public static string NewCharacter_Error_NoRace {
            get {
                return ResourceManager.GetString("NewCharacter_Error_NoRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing character type.
        /// </summary>
        public static string NewCharacter_Error_NoType {
            get {
                return ResourceManager.GetString("NewCharacter_Error_NoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot save.
        /// </summary>
        public static string NewCharacter_Exception_CannotSave {
            get {
                return ResourceManager.GetString("NewCharacter_Exception_CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Metamagic.
        /// </summary>
        public static string Spell_AddMetamagic {
            get {
                return ResourceManager.GetString("Spell_AddMetamagic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Prepared.
        /// </summary>
        public static string Spell_AddToPrepared {
            get {
                return ResourceManager.GetString("Spell_AddToPrepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expend Spell.
        /// </summary>
        public static string Spell_RemovePrepared {
            get {
                return ResourceManager.GetString("Spell_RemovePrepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Spell.
        /// </summary>
        public static string Spell_RemoveSpell {
            get {
                return ResourceManager.GetString("Spell_RemoveSpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Repository.
        /// </summary>
        public static string TabLabel_AllCharacters {
            get {
                return ResourceManager.GetString("TabLabel_AllCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Character.
        /// </summary>
        public static string TabLabel_NewCharacter {
            get {
                return ResourceManager.GetString("TabLabel_NewCharacter", resourceCulture);
            }
        }
    }
}
